### PR TITLE
Fix narrowing conversion error in dragonEye.h and goatEye.h

### PR DESCRIPTION
**Pull request by jeraymond**
Replace -0x001 with 0x000 to fix compile error:

    narrowing conversion of '-1' from 'int' to 'uint16_t {aka short unsigned int}' inside { } [-Wnarrowing]

This was occuring with Arduino 1.8.1 and Teenyduino 1.37 on macOS.

### CODE REVIEW

**Comment by jeraymond** [comment]
This fix allowed me to compile and run the project. The eyes themselves looked good with the is change.

**Comment by PaintYourDragon** [comment]
Whoa. Looks like a bug over in the convert script. I'll take a look and get to the bottom of this. Thanks for the heads-up!

**Comment by PaintYourDragon** [comment]
That was it! THANK YOU for spotting this. I was totally off-track with what I thought the problem was. Compiles with current Arduino & Teensyduino now!

Please fetch latest code. The correct values in those slots have values other than zero.

**Comment by jeraymond** [comment]
Thanks for the quick fix.

**Pull request closed without merging**
